# Generated by Django 5.0.4 on 2024-04-09 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('Account_Number', models.CharField(default='UMB5RVMZ1H', max_length=15)),
                ('Current_balence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction', models.CharField(choices=[('Withdraw', 'Withdraw'), ('Deposit', 'Deposit')], default='Withdraw', max_length=200)),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.users')),
            ],
        ),
    ]
