# Generated by Django 5.0.4 on 2024-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Account_Number',
            field=models.CharField(default='B1R2WALUXU', max_length=15),
        ),
    ]
