# Generated by Django 5.0.4 on 2024-04-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_users_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Account_Number',
            field=models.CharField(default='KI4WXL4D89', max_length=15),
        ),
    ]
